gujarat/urls.py
from django.urls import path
from gujarat.views import *
app_name='gujarat'
urlpatterns=[
    path('hardik/',hardik,name='hardik'),
]

mumbai/urls.py
from django.urls import path
from mumbai.views import *
app_name='mumbai'
urlpatterns=[
    path('rohith/',rohith,name='rohith'),
]

project16/urls.py
from django.contrib import admin
from django.urls import path,include
from kolkatta.views import *
import gujarat,mumbai 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('warner/',warner,name='warner'),
    path('hardik/',include('gujarat.urls')),
    path('rohith/',include('mumbai.urls')),

]

gujarat/models.py
from django.db import models

# Create your models here.

kolkatta/models.py
from django.db import models

# Create your models here.

mumbai/models.py
from django.db import models

# Create your models here.

gujarat/views.py
from django.shortcuts import render

# Create your views here.
def hardik(request):
    return render(request,'hardik.html')

kolkatta/views.py
from django.shortcuts import render

# Create your views here.
def warner(request):
    return render(request,'warner.html')

mumbai/views.py
from django.shortcuts import render

# Create your views here.
def rohith(request):
    return render(request,'rohith.html')

templates/hardik.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>gujarat page</h1>
        <h1>hello hardik</h1>
        <h1><a href="{% url 'mumbai:rohith' %}">go to mumbai page</a></h1>
        <h1><a href="{% url 'warner' %}">go to warner page</a></h1>


    </center>
    
</body>
</html>

templates/rohith.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Mumbai page</h1>
        <a href="{% url 'gujarat:hardik' %}"> go to gujarat page</a>
        <a href="{% url 'warner' %}">go to warner page</a>


    </center>
    
</body>
</html>

templates/warner.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>warner page</h1>
        <h1><a href="{% url 'gujarat:hardik' %}"> go to gujarat page</a></h1>
        <h1><a href="{% url 'mumbai:rohith' %}"> go to mumbai page</a></h1>


    </center>
    
</body>
</html>